baseURL = 'https://heiwig.com/'
languageCode = 'en-us'
title = 'Florian G. Heiwig'
relativeURLs = false
uglyURLs = false
disableKinds = ['taxonomy', 'term']

[params]
  description = "Berlin-based product professional, software developer, and entrepreneur."
  author = "Florian G. Heiwig"
  # Google Tag Manager container ID
  gtmContainerID = "GTM-MP6LZF49"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
